// <auto-generated />
namespace MySite.DataContexts.DecksMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class appuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201610171314194_app user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
